language: python
python:
  - "2.7"
before_install:
  - sudo locale-gen de_DE.UTF-8
install:
  - pip install -r requirements-dev.txt
  - python setup.py install
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=myria
  - bash .travis.sdist.sh
after_success:
  - coveralls
